### ISSUE TITLE
Landing Page: Database Configuration

### ISSUE THREAD

**Issue by ajbieber** [ajbieber/vision-aid-partners#14]
### Description
As part of the configurable landing page, we need to create a new table in our database that stores each new entry for the landing page. This table needs to store the **sanitized** text that will be displayed on the landing page, the user who created it, and the date which it was created.

### Definition of Done
- A new table is added to the database called `LandingPageEntry`
- The following rows need to be added
  - id (Int) should be auto incrementing
  - user (User) a relation field that relates back to the user object who created the post
  - creationDate (DateTime) when the post was created
  - content (String) the sanitized text that we can display on the landing page
- A new row should be added to the database to demonstrate its completion (please provide a screenshot)

**Comment by key-er** [comment]
1- setup
`CREATE TABLE LandingPageEntry ( id int AUTO_INCREMENT PRIMARY KEY, userID int, creationDate date,     content varchar(255),  CONSTRAINT fk_user FOREIGN KEY (userID) REFERENCES User(id) );`

2- insert
`insert into  LandingPageEntry  (userID, content, creationDate) values(8, "test..", CURRENT_DATE)`

3- retrieve:
`mysql> select * from LandingPageEntry inner join User uu on uu.id ;`

**Comment by key-er** [comment]
https://github.com/ajbieber/vision-aid-partners/pull/34
