### ISSUE TITLE
Landing Page: API

### ISSUE THREAD

**Issue by ajbieber** [ajbieber/vision-aid-partners#15]
### Description
As part of the landing page task, we will need to define API methods for the content. We will need a GET, POST, PATCH, and DELETE method. They will each do the following

- GET: Retrieves all landing page entries, sorted by date (most recent first).
- POST: Creates a new landing pages entry
- PATCH: Updates the `content` field of a specific landing page entry
- DELETE: Deletes a specific landing page entry

### Definition of Done
- All four API methods are defined.
- At least one unit/integration test is written for each API method to validate its functionality

**Comment by key-er** [comment]
https://github.com/ajbieber/vision-aid-partners/pull/46
