### ISSUE TITLE
Add GET and DELETE methods for landing page configuration

### ISSUE THREAD

**Issue by ajbieber** [ajbieber/vision-aid-partners#44]
### Description
While we have boiler plate code in place, there currently isnt any logic for retrieving or deleting entries from the database. We need to add this logic in so that the landing page API is fully functional.

### Definition of Done
- GET an DELETE endpoints are functional and tested

**Comment by key-er** [comment]
https://github.com/ajbieber/vision-aid-partners/pull/46
